apiVersion: v1
kind: Service
metadata:
  name: mcp-mem0
  namespace: mcp-mem0
spec:
  type: NodePort
  selector:
    app: mcp-mem0
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30850
      name: sse
