apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: letta
  namespace: letta
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - letta.dev.net
      secretName: tls-dev-net-wildcard
  rules:
    - host: letta.dev.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: letta
                port:
                  number: 8283
