apiVersion: v1
kind: Secret
metadata:
  name: letta-env
  namespace: letta
type: Opaque
stringData:
  LETTA_PG_URI: "postgresql://postgres:postgres123@postgresql-rw.postgresql.svc.cluster.local:5432/letta"
  OLLAMA_BASE_URL: "http://ollama.ollama.svc.cluster.local:11434/v1"
