apiVersion: v1
kind: Service
metadata:
  name: letta
  namespace: letta
spec:
  type: NodePort
  selector:
    app: letta
  ports:
    - port: 8283
      targetPort: 8283
      nodePort: 30283
      name: http
