apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/sins.yaml
    target:
      kind: Application
      name: sins
  - path: patches/certa.yaml
    target:
      kind: Application
      name: certa
  - path: patches/ollama.yaml
    target:
      kind: Application
      name: ollama
