apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella
  namespace: argocd
spec:
  source:
    helm:
      values: |
        global:
          env: dev
          domain: dev.net
          tlsSecret: tls-dev-net-wildcard
        mailu:
          nodeHosts: |
            10.11.4.11 k3s-control
            10.11.4.12 k3s-worker-1
            10.11.4.13 k3s-worker-2
            10.11.4.14 k3s-worker-3
        postgresql:
          pgadminHost: pgadmin.dev.net
        sins:
          haproxyIp: "10.11.4.17"
        rancher:
          hostname: rancher.dev.net
        eclipseCheOAuthSecret: "eJbBfIK2tHK2oT3n7Ff2HTZAWoeFI6C6"
        githubRunner:
          group: k3s-dev
          labels:
            - k3s
            - k3s-dev
        freeipa:
          hostname: ipa.dev.net
          realm: DEV.NET
          domain: dev.net
          credentialsSecret: freeipa-credentials
          ingressTlsSecret: tls-dev-net-wildcard
          adminPassword: "G86uyfdk"
          ldapServiceUserPassword: "KidaSvc2024!"
        sonarqubeChartRevision: "2026.2.0-176"
        keycloakOperatorChartRevision: "1.0.0-188"
