apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../manifests/sonarqube/namespace.yaml
  - ../../../manifests/sonarqube/postgresql-secret.yaml
  - ../../../manifests/sonarqube/configmap.yaml
  - ../../../manifests/sonarqube/deployment.yaml
  - ../../../manifests/sonarqube/service.yaml
  - ../../../manifests/sonarqube/ingress.yaml
patches:
  - target:
      kind: Ingress
      name: sonarqube-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: sonar.dev.net
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - sonar.dev.net
      - op: replace
        path: /spec/tls/0/secretName
        value: tls-dev-net-wildcard
